owner: ggscores 
repo: esports-data-provider-status 

sites:
  - name: APIV3-Teams
    url: https://apiv3.esports-data-provider.com/teams
    headers:
    - "token: ${{ secrets.TOKEN }}"
  - name: APIV3-Events
    url: https://apiv3.esports-data-provider.com/events
    headers:
    - "token: test"
  - name: APIV3-Matches
    url: https://apiv3.esports-data-provider.com/matches
    headers:
    - "token: test"
  - name: APIV3-VideoGames
    url: https://apiv3.esports-data-provider.com/videogames
    headers:
    - "token: test"


status-website:
  #cname: custom.domain
  baseUrl: /StatusAPI
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Esports Data Providers
  introTitle: "This is the **Esports Data Providers** status page ."
  introMessage: You can see the vitality of our API system 
  navbar:
    - title: Return
      href: https://staging-esportsdataprovider.kinsta.cloud
    - title: Status
      href: https://ggscores.github.io/esports-data-provider-status
